
---
- name: Deploy simple flask application
  hosts: localhost
  become: yes
  tasks:

    - name: Update the apt package cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - python3-pip
          - git
          - docker.io
        state: present

    - name: Clone Flask app repository from GitHub
      git:
        repo: 'https://github.com/VINITGG/Simple_Flask_app.git'
        dest: '/home/ubuntu/Simple_Flask_app/Ansible_deploy'

    - name: Install Python dependencies
      command: /home/ubuntu/Simple_Flask_app/venv/bin/pip install -r /home/ubuntu/Simple_Flask_app/requirements.txt
      args:
        chdir: /home/ubuntu/Simple_Flask_app

    - name: Build the Docker image
      command:
        cmd: docker-compose -f /home/ubuntu/Simple_Flask_app/docker-compose.yml build

    - name: Create Docker container using docker run
      command: "docker run -d --name myapp -p 5000:5000 myapp:3.9-slim"
      register: result


    - name: Check Docker container status
      command:
        cmd: docker ps
      register: docker_status

    - name: Display container activity and CPU utilization
      command: "timeout 10s docker stats --no-stream"
      register: result
