---
- name: Deploy simple flask application
  hosts: Aws kali machine
  become: yes
  tasks:

    - name: Update the apt package cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - python3-pip
          - git
          - docker.io
          - docker-compose
        state: present

    - name: Clone Flask app repository from GitHub
      git:
        repo: 'https://github.com/VINITGG/Simple_Flask_app.git'
        dest: '/home/kali/flask_app/deploy'

    - name: Install Python dependencies
      pip:
        requirements: /home/kali/flask_app/requirements.txt

    - name: Build the Docker image
      command:
        cmd: docker-compose -f /home/kali/flask_app/docker-compose.yml build

    - name: Start the Docker container
      command:
        cmd: docker-compose -f /home/kali/flask_app/docker-compose.yml up -d

    - name: Check Docker container status
      command:
        cmd: docker ps
      register: docker_status

    - name: Display container status
      debug:
        var: docker_status
